export class User{

    private _email: string = '';
    private _password: string = '';
    private _nickname: string = '';

    constructor(email: string, password: string, nickname: string){
        this._email = email;
        this._password = password;
        this._nickname = nickname;
        //ID not needed since it is auto-generated by Firebase
    }

    get email(): string{
        return this._email;
    }

    get password(): string{
        return this._password;
    }

    get nickname(): string{
        return this._nickname;
    }
}