export class User{

    private _email: string = '';
    private _password: string = '';

    constructor(email: string, password: string){
        this._email = email;
        this._password = password;
        //ID not needed since it is auto-generated by Firebase
    }

    get email(): string{
        return this._email;
    }

    get password(): string{
        return this._password;
    }
}